field: 9c69a4e9-5989-4f93-97e0-5b37ae3f0002 # Basic Form Fields
fieldLayouts:
  431efbe7-30b0-4c3f-8afb-abd23223d92b:
    tabs:
      -
        elements:
          -
            fieldUid: bb8b993f-020a-4c6c-9a47-2132193b4e3c # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 073bf6eb-4869-400c-8923-f128ec493ed8 # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ddac7416-7008-4913-9f41-4a1ca1963477 # Options
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1e7bf913-c46a-4b6a-80d2-57d6ae119428 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1e7bf913-c46a-4b6a-80d2-57d6ae119428: # Required
    columnSuffix: hqrdlkrv
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  073bf6eb-4869-400c-8923-f128ec493ed8: # Handle
    columnSuffix: sjuwwtwc
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  bb8b993f-020a-4c6c-9a47-2132193b4e3c: # Label
    columnSuffix: jpnrcowy
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  ddac7416-7008-4913-9f41-4a1ca1963477: # Options
    columnSuffix: maepnpkj
    contentColumnType: text
    fieldGroup: null
    handle: options
    instructions: ''
    name: Options
    searchable: true
    settings:
      addRowLabel: 'Add an option'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Option Label'
                -
                  - handle
                  - optionLabel
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Value
                -
                  - handle
                  - value
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: '1'
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
handle: dropdown
name: Dropdown
sortOrder: 3
