field: 9c69a4e9-5989-4f93-97e0-5b37ae3f0002 # Basic Form Fields
fieldLayouts:
  b02ec849-c628-4498-871a-0697775115f8:
    tabs:
      -
        elements:
          -
            fieldUid: 9b7a4407-37d7-4007-9ba4-1b83b3401d5f # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4ffaf42f-75bc-49b5-acf3-14844446e5ca # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4d381cbb-d097-4f67-a5ea-1ede995a56f1 # Min Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c3175e60-cd06-44f1-9b8f-ce8dd07bf523 # Max Value
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 136f0ed2-4e5b-4c5e-a663-3c164113fdf5 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4d381cbb-d097-4f67-a5ea-1ede995a56f1: # Min Value
    columnSuffix: uqwgvctr
    contentColumnType: integer(10)
    fieldGroup: null
    handle: minValue
    instructions: ''
    name: 'Min Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  4ffaf42f-75bc-49b5-acf3-14844446e5ca: # Handle
    columnSuffix: gndajzvc
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  9b7a4407-37d7-4007-9ba4-1b83b3401d5f: # Label
    columnSuffix: egnyseuz
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  136f0ed2-4e5b-4c5e-a663-3c164113fdf5: # Required
    columnSuffix: ylnnmpym
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  c3175e60-cd06-44f1-9b8f-ce8dd07bf523: # Max Value
    columnSuffix: kjizmpqw
    contentColumnType: integer(10)
    fieldGroup: null
    handle: maxValue
    instructions: ''
    name: 'Max Value'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
handle: number
name: Number
sortOrder: 5
