field: 36bd8ea1-0ab1-473e-9dd1-9eb5df03170a # Partners
fieldLayouts:
  f7684282-3039-43d4-930e-45564eae581d:
    tabs:
      -
        elements:
          -
            fieldUid: 4db0cd0c-6965-4801-8389-3327bb85ef7d # Partner Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 90b2d072-fa0e-4682-9e02-ccc4336cc75e # Partner Logo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 949cb20c-16fe-4890-ac92-9f1eff1e986c # Destination
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4db0cd0c-6965-4801-8389-3327bb85ef7d: # Partner Name
    columnSuffix: null
    contentColumnType: string(120)
    fieldGroup: null
    handle: partnerName
    instructions: ''
    name: 'Partner Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 30
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  90b2d072-fa0e-4682-9e02-ccc4336cc75e: # Partner Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: partnerLogo
    instructions: ''
    name: 'Partner Logo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:d05f331b-a986-43d1-b531-24faf2fe66ab' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: thumbs
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:d05f331b-a986-43d1-b531-24faf2fe66ab' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:d05f331b-a986-43d1-b531-24faf2fe66ab' # Uploads
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  949cb20c-16fe-4890-ac92-9f1eff1e986c: # Destination
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: destination
    instructions: ''
    name: Destination
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: partnerName
name: Partner
sortOrder: 1
