field: 9c69a4e9-5989-4f93-97e0-5b37ae3f0002 # Basic Form Fields
fieldLayouts:
  c9e212f5-ac24-4b99-a85e-1bacc0334240:
    tabs:
      -
        elements:
          -
            fieldUid: f4e30cad-4b29-425b-a7f8-15ca11c7ffd8 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ff5ce809-d8b0-47dc-a0ee-9fca30c8dc85 # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9082f0ac-ff2c-48bb-bd86-388de3ff4568 # Placeholder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a58acd3a-2712-41e9-9333-de0f7e439e38 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9082f0ac-ff2c-48bb-bd86-388de3ff4568: # Placeholder
    columnSuffix: vwknuzqj
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: ''
    name: Placeholder
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  a58acd3a-2712-41e9-9333-de0f7e439e38: # Required
    columnSuffix: ccfkarfe
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  f4e30cad-4b29-425b-a7f8-15ca11c7ffd8: # Label
    columnSuffix: uhuuzyah
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  ff5ce809-d8b0-47dc-a0ee-9fca30c8dc85: # Handle
    columnSuffix: lwdjikrq
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: singleLine
name: 'Single Line'
sortOrder: 1
