fieldLayouts:
  3379d8c8-26b9-4848-8422-ac63c92e8917:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 432d3808-7347-4e0f-9319-30e1b9267139 # Mission Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 992931b0-e2e5-473c-86c3-ff828afe1633 # Mission Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ca1f8b86-1417-4253-b735-8b94c98fe351 # Tag Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e87e65cf-3015-436b-8b7a-7c794debe425 # Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 63c94632-31e2-4267-94ec-9b2e1cc4f7d6 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: default
hasTitleField: false
name: Default
section: 4536aaf8-d823-440b-8df5-be2bcd40ca36 # VIP Stories
sortOrder: 1
titleFormat: '{missionTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
