columnSuffix: pdjfbhrw
contentColumnType: text
fieldGroup: c4ed709c-0b3f-4857-9ca5-a55a007bc9d0 # Homepage
handle: aboutRichText
instructions: ''
name: 'About Rich text'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - d05f331b-a986-43d1-b531-24faf2fe66ab # Uploads
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
