columnSuffix: null
contentColumnType: string
fieldGroup: b4c67b5a-c048-4b6f-918e-cc4b7167d5bd # Common
handle: featuredStory
instructions: ''
name: 'Featured Story'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Add a story'
  showSiteMenu: true
  source: null
  sources:
    - 'section:c3637e52-cfaa-4ad8-a366-953b89ecf1dd' # Stories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
