columnSuffix: null
contentColumnType: string
fieldGroup: b4c67b5a-c048-4b6f-918e-cc4b7167d5bd # Common
handle: menu
instructions: ''
name: Menu
searchable: false
settings:
  contentTable: '{{%matrixcontent_menu}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
