columnSuffix: mduzfsfx
contentColumnType: text
fieldGroup: 874073e7-a836-4fbe-adff-1c4aa25a30d7 # Common
handle: pageHeading
instructions: ''
name: 'Page Heading'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - d05f331b-a986-43d1-b531-24faf2fe66ab # Uploads
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
