columnSuffix: dbpsrqjf
contentColumnType: smallint(2)
fieldGroup: 874073e7-a836-4fbe-adff-1c4aa25a30d7 # Common
handle: paginationLimit
instructions: ''
name: 'Pagination Limit'
searchable: false
settings:
  decimals: 0
  defaultValue: 9
  max: 20
  min: 3
  prefix: null
  previewCurrency: ''
  previewFormat: none
  size: '1'
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
