columnSuffix: null
contentColumnType: string
fieldGroup: b4c67b5a-c048-4b6f-918e-cc4b7167d5bd # Common
handle: slider
instructions: ''
name: Slider
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:c71752a5-03bb-44e0-b7cc-ab999a652db5' # uploads
  defaultUploadLocationSubpath: ''
  limit: '5'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:c71752a5-03bb-44e0-b7cc-ab999a652db5' # uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:c71752a5-03bb-44e0-b7cc-ab999a652db5' # uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
