dateModified: 1660406457
email:
  fromEmail: thegrandt06@gmail.com
  fromName: paranormax
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: email-smtp.us-east-1.amazonaws.com
    password: BG8DLbImrlBUtq+t5vbt1Ki7UZ1t0uwmWkYlAPC9JOLV
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: AKIA2S5TZFL32DS2B3VD
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    0b17ccce-0cf2-465a-9942-ad0cce43d49e: 'Initial Rows' # Initial Rows
    1b930560-b9e9-4d0e-80ce-3b158fdb3512: 'Profile Image FallBack' # Profile Image FallBack
    1bf80454-00c0-4166-b2d9-d5d8cc5aa6e4: Review # Review
    1cdca378-0f6c-4a06-b46c-8edd246da02c: paranormax # paranormax
    1e7bf913-c46a-4b6a-80d2-57d6ae119428: Required # Required
    1f1b824e-df4a-431f-b3f0-96f486962546: 'User Name' # User Name
    2d8d6613-cd91-465c-a603-3d5d0537cb6a: Handle # Handle
    2e1582a0-1841-4f17-8412-3dbfa206bd27: idk # idk
    2fdb9298-e860-4b44-853e-b8b21a2ff63f: 'Hero Image' # Hero Image
    2fe4da48-6e78-4cee-baee-77ef34186b13: New # New
    3cddd86a-3d5c-4af1-a3b6-80c40ee107f1: Handle # Handle
    3f435d06-03ff-4ae1-ba1a-3bb6b1dd1237: 'Assigned to' # Assigned to
    4b15a976-973d-4d9b-8077-a24cee21f9d0: Label # Label
    04c6e6c7-4298-42cb-a6c7-a3c9eba18d4f: 'About Rich text' # About Rich text
    4d5b7c01-a277-4a52-ac7e-85f9cfd98fdd: Default # Default
    4d381cbb-d097-4f67-a5ea-1ede995a56f1: 'Min Value' # Min Value
    4db0cd0c-6965-4801-8389-3327bb85ef7d: 'Partner Name' # Partner Name
    4ffaf42f-75bc-49b5-acf3-14844446e5ca: Handle # Handle
    5a232fcc-f94f-4553-b73e-f1c430d22f06: Contact # Contact
    5aaf1459-99d7-4cc4-a294-48eb45020f2e: Handle # Handle
    5c71d366-02b0-45cd-9b29-dce926e955fb: Options # Options
    5d0ab896-b6da-44a1-a339-de076a237c7e: 'Contact Blocks' # Contact Blocks
    6d8ff214-5f89-4d71-aca3-783bb085ca12: 'Image Fallback' # Image Fallback
    6dc508a7-7121-4dd3-a83e-4ca13c7b7ebf: craft # craft
    7ad53e3f-823e-4797-824a-190430ad474c: 'Setup Fee' # Setup Fee
    7b3f38a7-07a2-47c8-915a-7434de959e6d: Header # Header
    7f93787d-3ac0-4256-95b9-a0dfdefff70a: Footer # Footer
    8ab6ccaa-303f-41e6-b753-6d1864c45042: 'Partners Title' # Partners Title
    8d683f57-5a84-4647-bfde-84cd56e9f313: Register # Register
    8eabf134-d6fa-49cd-973b-e25921ceddd9: 'Custom Label' # Custom Label
    8edc8321-f61a-465b-ae54-97a0b205b412: Default # Default
    9a027a95-84a1-43ce-af50-96e5f3923f11: Default # Default
    9a53e480-7825-4274-8db1-803f1663eb1a: 'Hidden Value' # Hidden Value
    9a647386-7b45-4688-8a57-f32a09bcaafb: Homepage # Homepage
    9b7a4407-37d7-4007-9ba4-1b83b3401d5f: Label # Label
    9bd0e6c0-30ab-46b8-833a-78fc011625d7: Label # Label
    9c69a4e9-5989-4f93-97e0-5b37ae3f0002: 'Basic Form Fields' # Basic Form Fields
    9cdc4ad0-7fb2-4dac-af73-7ee2454651c1: Placeholder # Placeholder
    9d199beb-213b-47ee-a619-b900a730066a: Denied # Denied
    11f3e7b2-56e7-4bc1-9723-957528667225: 'Pagination Limit' # Pagination Limit
    18fddde8-8d22-41f5-b174-2f65ed065208: craft # craft
    28c8ceed-b0a0-4897-9c46-212f113e932f: 'Team Heading' # Team Heading
    36bd8ea1-0ab1-473e-9dd1-9eb5df03170a: Partners # Partners
    38a1184a-1381-426c-a931-63707475a816: Mission # Mission
    38b129f0-1856-4126-bc60-d5961302c76e: 'Missions Listing' # Missions Listing
    38d1940e-c00c-42e8-804a-e65e4f7b68ff: Required # Required
    45aba986-67e5-4410-9e78-1296cf93f459: Reviews # Reviews
    49b1289d-b21d-46d9-a0d9-6c6c050fc66b: 'General Image Fallback' # General Image Fallback
    53e5b3ad-dde8-4060-9cea-59e49a00e4db: Contact # Contact
    55dce432-0412-4fef-b4e8-07aa6bd5a955: 'VIP Content' # VIP Content
    56ed6e29-085c-4de3-8349-9d20cdd89c55: 'Contact Block Title' # Contact Block Title
    63c94632-31e2-4267-94ec-9b2e1cc4f7d6: 'Rich Text' # Rich Text
    073bf6eb-4869-400c-8923-f128ec493ed8: Handle # Handle
    77b7874a-949c-427f-b2cd-d916d5322190: Options # Options
    77e7f0e9-1c1e-4782-a7aa-85f4edc6819a: Missions # Missions
    81c0c49d-3126-4664-b4a1-ef1a1f3afb27: Homepage # Homepage
    87fe426b-8309-4fda-9505-c6134aec1419: 'Short Description' # Short Description
    90b2d072-fa0e-4682-9e02-ccc4336cc75e: 'Partner Logo' # Partner Logo
    136f0ed2-4e5b-4c5e-a663-3c164113fdf5: Required # Required
    218f7d4f-7514-47ab-a3f1-eae04f8c6513: Login # Login
    432d3808-7347-4e0f-9319-30e1b9267139: 'Mission Image' # Mission Image
    450e9eae-4f9e-4cc3-810a-51dd0b929320: 'Menu Label' # Menu Label
    480f298c-8b76-4ed1-919c-d9d3a2cebd76: Required # Required
    592d346d-3d64-4894-b222-0ffb3ae8c7df: 'Contact Block' # Contact Block
    949cb20c-16fe-4890-ac92-9f1eff1e986c: Destination # Destination
    955edc4f-19af-4537-b30e-4100e2cf4060: 'Review Heading' # Review Heading
    988d7fe1-6ad7-4a6d-9a5c-480bd13f8694: 'Mission Tag' # Mission Tag
    2025e822-001b-4fe4-bfa1-3a48415cad07: Destination # Destination
    2560cb9a-44d2-4de4-8800-ca8c910e6bd7: 'Page Heading' # Page Heading
    2725c006-6221-4c8f-a368-8ba20a1d2ae9: 'Recent Missions Title' # Recent Missions Title
    3676f1ca-7bb7-45a2-be88-804b1037e14e: 'Contact Block Content' # Contact Block Content
    4536aaf8-d823-440b-8df5-be2bcd40ca36: 'VIP Stories' # VIP Stories
    4949d671-6969-459e-a869-9454e2f27a0a: 'Add Plan' # Add Plan
    9082f0ac-ff2c-48bb-bd86-388de3ff4568: Placeholder # Placeholder
    25086d3c-8142-4a60-9c92-12c16dd70156: Icon # Icon
    27081b30-a9b1-43d4-94c5-60e38c61b511: 'Profile Info' # Profile Info
    29342b59-f4ec-4087-85a1-1c4a64b05353: 'Profile Info' # Profile Info
    65106a5d-b246-4bbb-93b1-b7fc8b867053: 'Pagination Limit' # Pagination Limit
    91755f15-4268-42d7-90c8-63806734cf8c: 'About Title' # About Title
    874073e7-a836-4fbe-adff-1c4aa25a30d7: Common # Common
    992931b0-e2e5-473c-86c3-ff828afe1633: 'Mission Title' # Mission Title
    3231610b-634b-4a5d-beae-96ae0a4d3c9d: 'Menu Item' # Menu Item
    57400620-74b9-4fd1-8134-95d444a675a1: 'Public Schema' # Public Schema
    a0e0e62e-c5e2-4764-9bc2-139c94fd83b7: Deadline # Deadline
    a1daf1c7-669c-4119-bf91-d436d5899cfd: 'Mission Status' # Mission Status
    a58acd3a-2712-41e9-9333-de0f7e439e38: Required # Required
    a95c7fc1-a7db-43e5-a0ce-d7b13eba732b: 'Contact Form' # Contact Form
    a12023cb-740a-4183-80f2-3310cb2da75d: 'Select Plan' # Select Plan
    ac7c91d0-f446-4ffd-9fe8-38fa922f5fae: VIP # VIP
    ac707a1f-e780-4db4-98f5-f8c19ea4ae63: Disclaimer # Disclaimer
    ac9329da-7d55-487f-a4b2-49179ad054b5: Destination # Destination
    b8cc4129-896c-4a08-97ec-4daea2e81855: Register # Register
    b88f7036-1b6c-4e4e-9a48-60ec011e3777: Rating # Rating
    b90d1a76-f7d4-4ec7-b033-35295bc63e48: 'Contact Info' # Contact Info
    b269cf29-d375-43fc-bb81-ad78ca103bd1: Partner # Partner
    ba8b49fa-df74-4296-a43b-458f8d350fba: Required # Required
    bb8b993f-020a-4c6c-9a47-2132193b4e3c: Label # Label
    bf952d95-a6a0-4614-9049-eea5d63687bb: 'Mediums Queue' # Mediums Queue
    c4ed709c-0b3f-4857-9ca5-a55a007bc9d0: Homepage # Homepage
    c8c997ad-5dcf-4f5e-8b99-d4a1b3082cab: VIP # VIP
    c3175e60-cd06-44f1-9b8f-ce8dd07bf523: 'Max Value' # Max Value
    c26437b6-6d58-4290-8d0b-799506f2776f: Label # Label
    c9730088-a7be-44cb-b088-f2b502b271b5: 'Hero Title' # Hero Title
    ca1f8b86-1417-4253-b735-8b94c98fe351: 'Tag Field' # Tag Field
    cbc6f4f5-dfe1-435d-8fe8-55975e97865c: Contact # Contact
    cf75ce3f-9af3-4777-9e98-b750e82a0099: Footer # Footer
    d05f331b-a986-43d1-b531-24faf2fe66ab: Uploads # Uploads
    d08a52d7-b81a-481f-b10d-f051e701525a: 'Missions Listing' # Missions Listing
    d46ef333-3626-49e3-97c5-972bcd3319e0: Login # Login
    da009cfa-0fb2-4b88-8dc2-b36ecefb962e: 'Menu Items' # Menu Items
    dcf13bfc-ac9a-49de-8a86-ff3b7bed8647: 'Menu Label' # Menu Label
    dd4c832f-013d-40f3-8504-ac892ab4e12a: 'About Image' # About Image
    ddac7416-7008-4913-9f41-4a1ca1963477: Options # Options
    e87e65cf-3015-436b-8b7a-7c794debe425: 'Short Description' # Short Description
    e306e778-1d29-47b7-b017-36607e1f821f: 'Custom Content' # Custom Content
    e2048c77-84b6-4e9f-81b4-57f3096e1e08: Mediums # Mediums
    eab35bb1-5fb5-4f4b-b47d-abf56fbfc46d: 'Private Schema' # Private Schema
    ef2003a7-8d54-4878-abdd-dd55e978fa1a: paranormax # paranormax
    f4e30cad-4b29-425b-a7f8-15ca11c7ffd8: Label # Label
    f941304a-c434-4951-9b12-20fe6adef532: 'Profile Picture' # Profile Picture
    fa76bb61-2adf-4be8-8d1f-ada647f07809: Members # Members
    fd3ab4f4-8ee6-430d-867c-cc7b6900f1f4: Handle # Handle
    ff5ce809-d8b0-47dc-a0ee-9fca30c8dc85: Handle # Handle
plugins:
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: pro
    enabled: true
    licenseKey: S4Z9WMXWMV4YTMD54CNTL7VK
    schemaVersion: 3.6.4
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: null
      autoScroll: true
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      bypassSpamCheckOnLoggedInUsers: false
      clientDigestFrequency: 1
      clientDigestRecipients: null
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: null
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      exportHandlesAsNames: false
      exportLabels: false
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: flexbox.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: false
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: null
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: true
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: false
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      successTemplateDirectory: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: true
  graphql-authentication:
    edition: standard
    enabled: true
    licenseKey: P1533L8O2HCCOQ2PG3R35CCX
    schemaVersion: 1.1.0
    settings:
      activationEmailSent: 'You will receive an email if it matches an account in our system'
      allowRegistration: '1'
      allowedFacebookDomains: null
      allowedGoogleDomains: null
      allowedTwitterDomains: null
      appleClientId: null
      appleClientSecret: null
      appleRedirectUrl: null
      appleServiceId: null
      appleServiceSecret: null
      assetMutations: null
      assetNotFound: 'We couldn''t find any matching assets'
      assetQueries: null
      emailNotInScope: 'No email in scope'
      entryMutations: null
      entryNotFound: 'We couldn''t find any matching entries'
      entryQueries: null
      facebookAppId: null
      facebookAppSecret: null
      facebookEmailMismatch: 'Email address doesn''t match allowed Facebook domains'
      facebookRedirectUrl: null
      fieldRestrictions:
        __assoc__:
          -
            - schema-1
            -
              __assoc__:
                -
                  - aboutImage
                  - queryMutate
                -
                  - aboutRichText
                  - queryMutate
                -
                  - aboutTitle
                  - queryMutate
                -
                  - assignedTo
                  - queryMutate
                -
                  - deadline
                  - queryMutate
                -
                  - denied
                  - queryMutate
                -
                  - disclaimer
                  - queryMutate
                -
                  - imageFallback
                  - queryMutate
                -
                  - heroImage
                  - queryMutate
                -
                  - heroTitle
                  - queryMutate
                -
                  - menuItems
                  - queryMutate
                -
                  - missionImage
                  - queryMutate
                -
                  - missionStatus
                  - queryMutate
                -
                  - missionTitle
                  - queryMutate
                -
                  - pageHeading
                  - queryMutate
                -
                  - paginationLimit
                  - queryMutate
                -
                  - partners
                  - queryMutate
                -
                  - partnersTitle
                  - queryMutate
                -
                  - profileImageFallback
                  - queryMutate
                -
                  - recentMissionsTitle
                  - queryMutate
                -
                  - reviewHeading
                  - queryMutate
                -
                  - reviews
                  - queryMutate
                -
                  - richText
                  - queryMutate
                -
                  - shortDescription
                  - queryMutate
                -
                  - tagField
                  - queryMutate
                -
                  - teamHeading
                  - queryMutate
          -
            - schema-2
            -
              __assoc__:
                -
                  - aboutImage
                  - queryMutate
                -
                  - aboutRichText
                  - queryMutate
                -
                  - aboutTitle
                  - queryMutate
                -
                  - assignedTo
                  - queryMutate
                -
                  - deadline
                  - queryMutate
                -
                  - denied
                  - queryMutate
                -
                  - disclaimer
                  - queryMutate
                -
                  - imageFallback
                  - queryMutate
                -
                  - heroImage
                  - queryMutate
                -
                  - heroTitle
                  - queryMutate
                -
                  - menuItems
                  - queryMutate
                -
                  - missionImage
                  - queryMutate
                -
                  - missionStatus
                  - queryMutate
                -
                  - missionTitle
                  - queryMutate
                -
                  - pageHeading
                  - queryMutate
                -
                  - paginationLimit
                  - queryMutate
                -
                  - partners
                  - queryMutate
                -
                  - partnersTitle
                  - queryMutate
                -
                  - profileImageFallback
                  - queryMutate
                -
                  - recentMissionsTitle
                  - queryMutate
                -
                  - reviewHeading
                  - queryMutate
                -
                  - reviews
                  - queryMutate
                -
                  - richText
                  - queryMutate
                -
                  - shortDescription
                  - queryMutate
                -
                  - tagField
                  - queryMutate
                -
                  - teamHeading
                  - queryMutate
      forbiddenField: 'User doesn''t have permission to access requested field(s)'
      forbiddenMutation: 'User doesn''t have permission to perform this mutation'
      googleClientId: null
      googleEmailMismatch: 'Email address doesn''t match allowed Google domains'
      googleTokenIdInvalid: 'Invalid Google Token ID'
      granularSchemas: null
      invalidEmailAddress: 'Invalid email address'
      invalidHeader: 'Invalid Authorization Header'
      invalidJwtSecretKey: 'Invalid JWT Secret Key'
      invalidLogin: 'We couldn''t log you in with the provided details'
      invalidOauthToken: 'Invalid OAuth Token'
      invalidPasswordMatch: 'New passwords do not match'
      invalidPasswordUpdate: 'We couldn''t update the password with the provided details'
      invalidRefreshToken: 'Invalid Refresh Token'
      invalidRequest: 'Cannot validate request'
      invalidSchema: 'No schema has been set for this user group'
      invalidUserUpdate: 'We couldn''t update the user with the provided details'
      jwtExpiration: '30 minutes'
      jwtRefreshExpiration: '3 months'
      jwtSecretKey: HmasVVZuLIGCKav9-mhsATSxPely2Ot4
      passwordResetSent: 'You will receive an email if it matches an account in our system'
      passwordSaved: 'Successfully saved password'
      passwordUpdated: 'Successfully updated password'
      permissionType: single
      sameSitePolicy: strict
      schemaId: '2'
      siteId: null
      tokenNotFound: 'We couldn''t find any matching tokens'
      twitterApiKey: null
      twitterApiKeySecret: null
      twitterEmailMismatch: 'Email address doesn''t match allowed Twitter domains'
      twitterRedirectUrl: null
      userActivated: 'Successfully activated user'
      userGroup: '3'
      userNotActivated: 'Please activate your account before logging in'
      userNotFound: 'We couldn''t find any matching users'
      volumeNotFound: 'We couldn''t find any matching volumes'
  mollie-payments:
    edition: standard
    enabled: true
    licenseKey: JT900JED8IE6UCLUA65LV607
    schemaVersion: 1.4.0
    settings:
      apiKey: $PAYMENT_API_KEY
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: pro
  live: true
  name: paranormax
  retryDuration: null
  schemaVersion: 3.7.8
  timeZone: Europe/Brussels
