fieldLayouts:
  5cbc9ffc-af1f-415d-b817-d9a91a1587cb:
    tabs:
      -
        elements:
          -
            fieldUid: 6cff1681-be7f-444d-a4ec-134bdddf2bcb # Disclaimer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: footer
name: Footer
sortOrder: 1
