fieldLayouts:
  2998ec3b-f48f-4d29-ac4d-1aca22cec32b:
    tabs:
      -
        elements:
          -
            fieldUid: d104bbcd-3870-4959-be5d-3b6646e8c788 # Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Navigation
        sortOrder: 1
handle: header
name: Header
sortOrder: 1
