fieldLayouts:
  bfdc10f5-cff1-4891-be5f-b4215ed4eecd:
    tabs:
      -
        elements:
          -
            fieldUid: 49b1289d-b21d-46d9-a0d9-6c6c050fc66b # General Image Fallback
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b930560-b9e9-4d0e-80ce-3b158fdb3512 # Profile Image FallBack
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: imageFallback
name: 'Image Fallback'
sortOrder: 3
