defaultPlacement: end
enableVersioning: true
handle: missionsListing
name: 'Missions Listing'
propagationMethod: all
siteSettings:
  1cdca378-0f6c-4a06-b46c-8edd246da02c: # paranormax
    enabledByDefault: true
    hasUrls: true
    template: missions/index.twig
    uriFormat: missions
type: single
