defaultPlacement: end
enableVersioning: true
handle: storiesListing
name: 'Stories Listing'
propagationMethod: all
siteSettings:
  6dc508a7-7121-4dd3-a83e-4ca13c7b7ebf: # craft
    enabledByDefault: true
    hasUrls: true
    template: stories/index
    uriFormat: stories
type: single
