defaultPlacement: end
enableVersioning: true
handle: vipStories
name: 'VIP Stories'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1cdca378-0f6c-4a06-b46c-8edd246da02c: # paranormax
    enabledByDefault: true
    hasUrls: true
    template: _vip\entry
    uriFormat: 'vip/{slug}'
type: channel
